options:
  num_point_quads: 1
  
  # Scene sampling mode 0 = center of each face
  # scene sampling mode 1 = num_rays surface points randomly uniformly across faces of specified model, or all of them (don't specify model)
  # scene sampling mode 2 = num_rays surface points, within sample_distance of a random vertex on specified model (or random model if unspecified)
  scene_sampling_mode: 1
  num_rays: 100 # if using random scene point sampling, sample this many points
  sample_distance: 0.05
  sample_model: 0  
  num_hod_bins: 5
  max_hod_dist: 0.1

  gurobi_int_options:
    #MIPFocus: 1
    PoolSearchMode: 2
    PoolSolutions: 10

  gurobi_float_options:
    TimeLimit: 300
    #PoolGap: 0.00
    #FeasRelaxBigM: 100
    #MIPGap: 0.00
    #Heuristics: 0.05
 
models:
  - name: "TriangularPrism"
    vertices:
      px: [0.1, 0.0, 0.0] 
      nx: [-0.1, 0.0, 0.0] 
      py: [0.0, 0.1, 0.0] 
      ny: [0.0, -0.1, 0.0] 
      pz: [0.0, 0.0, 0.1]
      nz: [0.0, 0.0, -0.05] 
    faces: # clockwise from outside
      pxpynz: ["px", "nz", "py"]
      pxpypz: ["px", "py", "pz"]
      nxpynz: ["nx", "pz", "py"]
      nxpypz: ["nx", "py", "nz"]
      nxnynz: ["nx", "nz", "ny"]
      nxnypz: ["nx", "ny", "pz"]
      pxnynz: ["px", "ny", "nz"]
      pxnypz: ["nx", "pz", "ny"]
    scene_tf: [0.7, 0, 0.2, 0, 0.5, 0.5]
    model_tf: [0.0, 0, 0.3, 0, 0.0, 0.0]